### ISSUE TITLE
"Media File is Missing" on images from Lightroom 5 collection

### ISSUE THREAD

**Issue by derpoliuk** [iMediaSandboxing/iMedia#54]
I have issue with parsing Lightroom 5 catalog. Here are steps to reproduce:
1. Create new catalog in Lightroom 5. 
2. Add pictures to new catalog (IMPORTANT: not all thumbnails are generated at this moment).
   ![screen shot 2014-10-01 at 11 44 52](https://cloud.githubusercontent.com/assets/1434418/4473589/fd2b1aac-4954-11e4-87e9-f143575de810.png)
3. Run iMediaTester project. It picks up latest catalog from Lightroom.
4. All images without thumbnail in Lightroom are marked as "Media File is Missing".
   ![screen shot 2014-10-01 at 11 44 42](https://cloud.githubusercontent.com/assets/1434418/4473590/0049f1a4-4955-11e4-8035-d72230d01f78.png)

**Comment by gloubibou** [comment]
The Lightroom parser sets an error message on the IMBObject when it fails to load the preview image from the pyramid file.

Commit d3dc7bce55d59346a63f7b13c8f3bf79ff3363ad makes sure that is preserved so it can be displayed. Previously a generic "Media File is Missing" message was shown.

iMedia 2.x falls back to displaying the master image when there is a problem with the pyramid file. This may look better, but can have iMedia show and use unedited images.

**Comment by jjac** [comment]
Works as designed.
