### ISSUE TITLE
Images in media browser not ordered as in "Photos" 

### ISSUE THREAD

**Issue by iljaiwas** [iMediaSandboxing/iMedia#62]
I'm not sure if this is something that could be fixed in iMedia, or of this is a bug in Apple's parser. Any ideas?

Here is a post from a user:

>For example, I take a picture of book, front, back and inside, then i take a picture of another book, front >back and inside. put it in photos, label the album. I open up garage sale, start a new template(auction) >click on the media button. the photos show up on the left side window, i click the album i want and the >pictures have been rearranged. I have to search through all of the pictures to find the ones that go with >each book. They are not in the order they were taken or put into photos. They are out of order. As you >can imagine, with over 100 photos it is almost impossible to manage. Thanks for fixing this.

[Link to thread on the GarageSale user group] (https://help.iwascoding.com/t/how-do-i-import-photos-from-the-updated-photo-program/406/9?u=ilja)

**Comment by jjac** [comment]
Could you provide a screenshot showing the order of images in Photos App versus the image order in Photos library of GarageSale media browser? So far, I have not seen a different order between Photos and iMedia myself regarding my own libraries.

**Comment by jjac** [comment]
@iljaiwas Please verify proposed fix with customer.

**Comment by iljaiwas** [comment]
Fixed by your fix, according to customer:
https://help.iwascoding.com/t/how-do-i-import-photos-from-the-updated-photo-program/406/13?u=ilja
