### ISSUE TITLE
MediaBrowser is empty when Photos is open

### ISSUE THREAD

**Issue by iljaiwas** [iMediaSandboxing/iMedia#76]
I think we are using Apple's Photos library parser. Could this be the reason that the Media Browser window stays completely empty when Photos is open? If so, a warning would be nice.

**Comment by jjac** [comment]
No, it should be populated no matter whether the Photos app is currently running or not.

Also, I have never encountered such problem.

**Comment by iljaiwas** [comment]
Thanks for the reply. I'll dig into it and see what I can find out.

**Comment by iljaiwas** [comment]
I swichted the iMedia Tester app to use Apple's photos parser, and then I get this screen:

![screen shot 2016-03-03 at 11 32 56](https://cloud.githubusercontent.com/assets/2284114/13491630/cf526d92-e133-11e5-8bec-20c298e8c0ee.png)

With the iMedia's own parser the Photos library is fine. Guess it's time to ditch Apple's parser. :(

**Comment by jjac** [comment]
@iljaiwas Is this issue still relevant? If not, please close. Definitely, IMBAppleMediaLibraryParser should work with iPhoto – and does within our app.

**Comment by iljaiwas** [comment]
Almost a year, cannot remember. Closing this issue for now. Will open again if I run into this again.
