### ISSUE TITLE
Node tree badges draw too close to edge of view

### ISSUE THREAD

**Issue by danielpunkass** [iMediaSandboxing/iMedia#83]
There is an issue with the computation of the badge rect, which causes the badge icons to draw too close, even partially off the edge of the view.

Patch forthcoming.

<img width="143" alt="media_and_drag_media_here__sandboxed_" src="https://cloud.githubusercontent.com/assets/14606/19479809/787f40d4-9516-11e6-94c0-cd88dcdf3bad.png">

**Comment by danielpunkass** [comment]
For the record: a good way to reproduce this bug is to arrange for some security-scope-bookmarked access content in the list, and then temporarily comment out the code that would re-load that bookmark from disk: add a return; statement at the start of -[IMBAccessRightsController loadFromPrefs]

**Comment by jjac** [comment]
Fixed with effc5fd
