### ISSUE TITLE
MediaLibrary.framework & iCloud Photos Library

### ISSUE THREAD

**Issue by haoxi911** [iMediaSandboxing/iMedia#88]
Hello,

I am working on a project to export user's photos from Photos Library, and I am trying to figure out if I can use iMedia. 

I just have 2 very high level questions, could anyone please take a look?

1) I will need to support `iCloud Photos Library`, is it supported by MediaLibrary.framework now?
2) Can I use  MediaLibrary.framework without sandboxing it? Or is it the major reason this fork being created?

Thanks!
Kevin

**Comment by jjac** [comment]
@haoxi911 you posted an extended version of this question also on the iMedia mailing list where it indeed seems more appropriate. We have not explicitly stated this anywhere but we use GitHub's issue tracker for tracking issues with the framework.
